import type { ProductReview } from "./types";

export const products: ProductReview[] = [
  {
    slug: "premium-wireless-earbuds-bass-boost-9000",
    productName: "UltraBass Pro X9000 TWS Earbuds",
    brand: "SoundKing",
    category: "Electronics",
    images: {
      official: [
        "https://picsum.photos/seed/earbuds-official-1/400/400",
        "https://picsum.photos/seed/earbuds-official-2/400/400",
      ],
      review: [
        "https://picsum.photos/seed/earbuds-review-1/400/400",
        "https://picsum.photos/seed/earbuds-review-2/400/400",
      ],
    },
    sellerRating: 4.5,
    realityScore: 2.1,
    totalReviews: 12847,
    fakeReviewPercent: 68,
    price: "₹1,299",
    source: "amazon.in",
    sarcasticVerdict:
      "Congratulations! You found earbuds where the bass boost is actually just distortion, and the 'Pro' stands for 'Probably Returns Only'.",
    whatTheySay: "Amazing sound quality with deep bass. Best earbuds under ₹2000!",
    whatTheyMean:
      "I got these free for a 5-star review and haven't actually listened to music since 2019.",
    serviceMetrics: {
      returnPolicy: "7-day return",
      returnSuccessRate: 34,
      deliveryRating: 3.8,
      customerSupportScore: 1.2,
      sellerResponseTime: "3-5 business days (or never)",
      sarcasticServiceVerdict:
        "Return policy exists on paper. In reality, the seller ghosts you faster than your Tinder match. Customer support replies with 'kindly adjust' to every complaint.",
    },
    aiAnalysis: {
      sentimentBreakdown: {
        genuine: 18,
        suspicious: 32,
        copypasta: 28,
        bribed: 22,
      },
      topSarcasticInsight:
        "68% of reviews were posted within 48 hours of purchase. Either these earbuds deliver enlightenment on first listen, or someone's running a review farm.",
      realPros: [
        "Cheap enough that losing them isn't a tragedy",
        "Bluetooth actually connects (sometimes)",
        "Case has a satisfying click",
      ],
      realCons: [
        "Bass boost is just volume boost with extra distortion",
        "Battery lasts 2 hours, not the advertised 40",
        "Touch controls activate when you breathe near them",
        "Left earbud disconnects if you turn your head",
      ],
      buyOrCry: "cry",
    },
    reviews: [
      {
        author: "TechGuru_Mumbai",
        rating: 5,
        text: "Best earbuds I have ever used in my life! Sound quality is out of this world. Must buy for everyone!",
        sarcasticTranslation:
          "I have used exactly one pair of earbuds in my life, and these are technically the best by default. Also, the seller is my cousin.",
        flagged: "bribed",
      },
      {
        author: "verified_buyer_2847",
        rating: 5,
        text: "Good product. Nice quality. Fast delivery. Recommended.",
        sarcasticTranslation:
          "This review was generated by an AI that learned English from product listings. Notice the lack of any specific detail about the actual product.",
        flagged: "copypasta",
      },
      {
        author: "DisappointedDad",
        rating: 2,
        text: "Bought for my son. Left earbud stopped working after 3 days. Bass is just loud static. Returning.",
        sarcasticTranslation:
          "The only honest review in a sea of propaganda. This person actually used the product. Revolutionary concept.",
        flagged: "genuine",
      },
      {
        author: "AudiophileRaj",
        rating: 1,
        text: "These sound like two tin cans connected by a wet noodle. The 'noise cancellation' just means one earbud stops working randomly.",
        sarcasticTranslation:
          "A poet among reviewers. Accurate and eloquent. The tin can comparison might actually be unfair to tin cans.",
        flagged: "genuine",
      },
    ],
  },
  {
    slug: "miracle-face-cream-anti-aging-glow",
    productName: "GlowMax 360° Youth Restore Cream",
    brand: "DermaGlow",
    category: "Beauty & Personal Care",
    images: {
      official: [
        "https://picsum.photos/seed/cream-official-1/400/400",
        "https://picsum.photos/seed/cream-official-2/400/400",
      ],
      review: [
        "https://picsum.photos/seed/cream-review-1/400/400",
        "https://picsum.photos/seed/cream-review-2/400/400",
      ],
    },
    sellerRating: 4.3,
    realityScore: 1.8,
    totalReviews: 8932,
    fakeReviewPercent: 74,
    price: "₹499",
    source: "flipkart",
    sarcasticVerdict:
      "This cream promises to make you look 20 years younger. Spoiler: It's moisturizer with glitter. The only thing getting a glow-up is the seller's bank account.",
    whatTheySay:
      "After just 2 days my skin is glowing! All my wrinkles are gone! My husband can't recognize me!",
    whatTheyMean:
      "I applied so much cream that the reflection off the grease makes me look luminous. My husband can't recognize me because I've been in the bathroom for 6 hours.",
    serviceMetrics: {
      returnPolicy: "10-day return (Flipkart Assured)",
      returnSuccessRate: 28,
      deliveryRating: 4.1,
      customerSupportScore: 1.5,
      sellerResponseTime: "24 hours (auto-reply only)",
      sarcasticServiceVerdict:
        "Flipkart Assured means the delivery is assured, not the quality. Try returning this and you'll get a refund in 'Flipkart SuperCoins' — the cryptocurrency nobody asked for.",
    },
    aiAnalysis: {
      sentimentBreakdown: {
        genuine: 12,
        suspicious: 38,
        copypasta: 30,
        bribed: 20,
      },
      topSarcasticInsight:
        "74% of 5-star reviewers have only ever reviewed DermaGlow products. Either this brand inspires cult-like devotion, or there's a factory of fake accounts somewhere in Lucknow.",
      realPros: [
        "Smells decent (like a mall perfume counter)",
        "Actually moisturizes (because it IS just moisturizer)",
        "Nice jar, can be reused for pickles",
      ],
      realCons: [
        "Zero anti-aging properties (dermatologist confirmed)",
        "'Natural ingredients' include things a chemist can't pronounce",
        "Causes breakouts for oily skin",
        "Before/after photos are just lighting changes",
      ],
      buyOrCry: "cry",
    },
    reviews: [
      {
        author: "GlowQueen_Delhi",
        rating: 5,
        text: "OMG!!! This cream changed my life!!! I look 18 again!!! All my friends are asking my secret!!! Must buy!!! ❤️❤️❤️",
        sarcasticTranslation:
          "The excessive exclamation marks are directly proportional to how fake this review is. Mathematical fact.",
        flagged: "bribed",
      },
      {
        author: "SkincareJunkie",
        rating: 5,
        text: "Very good cream. Skin is soft. Nice packaging. Good for gifting. Fast delivery by Flipkart.",
        sarcasticTranslation:
          "A review so generic it could be about literally any cream, soap, or even a book. Fast delivery is not a property of the cream.",
        flagged: "copypasta",
      },
      {
        author: "DermatologistWife",
        rating: 1,
        text: "My husband is a dermatologist. He looked at the ingredients and laughed for 5 minutes. It's basically Vaseline with food coloring.",
        sarcasticTranslation:
          "When a dermatologist's spouse is roasting your product, you know you've achieved peak skincare comedy.",
        flagged: "genuine",
      },
    ],
  },
  {
    slug: "smart-watch-fitness-tracker-military-grade",
    productName: "TactiWatch Pro Military Grade Smartwatch",
    brand: "StealthFit",
    category: "Electronics",
    images: {
      official: [
        "https://picsum.photos/seed/watch-official-1/400/400",
        "https://picsum.photos/seed/watch-official-2/400/400",
      ],
      review: [
        "https://picsum.photos/seed/watch-review-1/400/400",
        "https://picsum.photos/seed/watch-review-2/400/400",
      ],
    },
    sellerRating: 4.1,
    realityScore: 2.4,
    totalReviews: 5621,
    fakeReviewPercent: 58,
    price: "₹2,499",
    source: "both",
    sarcasticVerdict:
      "A 'military grade' watch that can't survive a light drizzle. The fitness tracker counts arm movements while eating as 'steps'. Your mother was right — you can't buy quality for ₹2,499.",
    whatTheySay:
      "Incredible smartwatch! GPS, heart rate, SpO2, military grade build. Apple Watch killer!",
    whatTheyMean:
      "The GPS thinks I'm in Pakistan when I'm in Pune. The heart rate monitor says I'm dead when I'm sleeping. But hey, it was cheap!",
    serviceMetrics: {
      returnPolicy: "7-day return (both platforms)",
      returnSuccessRate: 45,
      deliveryRating: 3.2,
      customerSupportScore: 2.1,
      sellerResponseTime: "2-4 business days",
      sarcasticServiceVerdict:
        "StealthFit's customer support is as stealthy as their brand name — you'll never find them. When they do respond, it's a copy-paste FAQ link that doesn't answer your question.",
    },
    aiAnalysis: {
      sentimentBreakdown: {
        genuine: 24,
        suspicious: 28,
        copypasta: 26,
        bribed: 22,
      },
      topSarcasticInsight:
        "The term 'military grade' here means it survived being dropped once on carpet. Also, 42% of reviewers posted the exact same photo of the watch on a muscular arm that is clearly not theirs.",
      realPros: [
        "Looks decent in photos (reality may vary)",
        "Battery lasts 3 days (if you don't use any features)",
        "Step counter works (overestimates by 40% but who's counting)",
      ],
      realCons: [
        "'Military grade' = marketing buzzword, nothing certified",
        "Heart rate sensor is essentially a random number generator",
        "Water resistant until it touches water",
        "Notifications arrive 5 minutes late",
        "App requires permissions to read your soul",
      ],
      buyOrCry: "maybe",
    },
    reviews: [
      {
        author: "FitnessFreak_BLR",
        rating: 5,
        text: "This watch is a game changer! I've lost 10 kgs since buying it! Best fitness tracker!",
        sarcasticTranslation:
          "Correlation is not causation. You lost weight because you started running, not because of a ₹2,499 watch. The watch just watched.",
        flagged: "suspicious",
      },
      {
        author: "WatchCollector",
        rating: 3,
        text: "Decent for the price. Don't expect Apple Watch quality. Screen is okay, notifications work sometimes. Good as a basic watch.",
        sarcasticTranslation:
          "Finally, a reviewer with expectations calibrated to reality. This person understands that ₹2,499 buys a ₹2,499 experience.",
        flagged: "genuine",
      },
      {
        author: "ReturnKing",
        rating: 1,
        text: "Screen cracked when I sneezed near it. Military grade my foot. The only thing military about this is how fast I'm retreating to the return page.",
        sarcasticTranslation:
          "ReturnKing speaks truth. The military grade certification was apparently issued by the seller's pet hamster.",
        flagged: "genuine",
      },
    ],
  },
  {
    slug: "organic-green-tea-weight-loss-detox",
    productName: "SlimLeaf Organic Green Tea - 28 Day Detox",
    brand: "HerbVeda",
    category: "Grocery & Gourmet",
    images: {
      official: [
        "https://picsum.photos/seed/tea-official-1/400/400",
        "https://picsum.photos/seed/tea-official-2/400/400",
      ],
      review: [
        "https://picsum.photos/seed/tea-review-1/400/400",
        "https://picsum.photos/seed/tea-review-2/400/400",
      ],
    },
    sellerRating: 4.6,
    realityScore: 2.8,
    totalReviews: 15234,
    fakeReviewPercent: 52,
    price: "₹349",
    source: "amazon.in",
    sarcasticVerdict:
      "It's tea. It's green. It will not, however, magically delete the samosas you had for lunch. The only thing getting 'detoxed' here is your wallet.",
    whatTheySay:
      "Lost 5 kgs in one week just by drinking this tea! No exercise needed!",
    whatTheyMean:
      "I also started eating only salads and running 5km daily but sure, it was definitely the tea.",
    serviceMetrics: {
      returnPolicy: "30-day return",
      returnSuccessRate: 62,
      deliveryRating: 4.4,
      customerSupportScore: 3.2,
      sellerResponseTime: "Within 24 hours",
      sarcasticServiceVerdict:
        "Surprisingly decent service — probably because tea is cheap enough that refunding you doesn't hurt. The 30-day return window is generous, but then again, you'll finish the tea before you realize it didn't make you thin.",
    },
    aiAnalysis: {
      sentimentBreakdown: {
        genuine: 32,
        suspicious: 24,
        copypasta: 22,
        bribed: 22,
      },
      topSarcasticInsight:
        "52% of weight loss claims in reviews exceed what is medically possible from drinking tea. Unless this tea contains a portal to another dimension where calories don't exist.",
      realPros: [
        "It IS actually tea (sets a low bar, clears it)",
        "Mild pleasant flavor if you don't expect miracles",
        "Good for hydration (because it's water with leaves)",
      ],
      realCons: [
        "Will not make you lose weight by itself (tea is not magic)",
        "'Organic' certification is from a website that no longer exists",
        "Detox is not a real medical concept for tea",
        "Premium pricing for regular green tea",
      ],
      buyOrCry: "maybe",
    },
    reviews: [
      {
        author: "YogaMom_Jaipur",
        rating: 5,
        text: "This tea is a blessing! I've been drinking it for 28 days and I feel so light and energetic! My skin is glowing too!",
        sarcasticTranslation:
          "The placebo effect is strong with this one. Feeling 'light' after 28 days of drinking tea is called 'being hydrated'. Welcome to science.",
        flagged: "suspicious",
      },
      {
        author: "TeaSnob",
        rating: 3,
        text: "It's okay green tea. Nothing special about it. Tastes like every other green tea. The weight loss claims are BS — I gained 2 kgs.",
        sarcasticTranslation:
          "A person with taste buds AND critical thinking skills. The gained 2 kgs are a chef's kiss of irony.",
        flagged: "genuine",
      },
    ],
  },
  {
    slug: "portable-bluetooth-speaker-thunderbass",
    productName: "ThunderBass X500 Portable Speaker",
    brand: "BoomBox",
    category: "Electronics",
    images: {
      official: [
        "https://picsum.photos/seed/speaker-official-1/400/400",
        "https://picsum.photos/seed/speaker-official-2/400/400",
      ],
      review: [
        "https://picsum.photos/seed/speaker-review-1/400/400",
        "https://picsum.photos/seed/speaker-review-2/400/400",
      ],
    },
    sellerRating: 4.2,
    realityScore: 3.1,
    totalReviews: 7845,
    fakeReviewPercent: 45,
    price: "₹899",
    source: "both",
    sarcasticVerdict:
      "For ₹899, you get a speaker that plays music AND provides a free percussion show when the bass makes the plastic rattle. Multitasking!",
    whatTheySay:
      "Unbelievable sound! My neighbors can hear it clearly! Party speaker!",
    whatTheyMean:
      "My neighbors filed a noise complaint but technically that proves the volume works.",
    serviceMetrics: {
      returnPolicy: "7-day return (both platforms)",
      returnSuccessRate: 55,
      deliveryRating: 3.9,
      customerSupportScore: 2.8,
      sellerResponseTime: "1-2 business days",
      sarcasticServiceVerdict:
        "BoomBox has okay-ish service for the price range. Returns work if you're persistent enough. Customer support will ask you to 'try restarting the device' for literally every problem, including a cracked shell.",
    },
    aiAnalysis: {
      sentimentBreakdown: {
        genuine: 35,
        suspicious: 22,
        copypasta: 25,
        bribed: 18,
      },
      topSarcasticInsight:
        "Surprisingly, 35% of reviews are genuine here. The secret? At ₹899, expectations are already on the floor, making it hard to be disappointed.",
      realPros: [
        "Actually loud for the price",
        "Bluetooth connects without drama",
        "USB-C charging (welcome to the 21st century)",
        "Survives minor drops (the floor, not a cliff)",
      ],
      realCons: [
        "Bass rattles at 70% volume",
        "Battery life: 4 hours (advertised: 12 hours)",
        "'Waterproof' means splash-proof at best",
        "Built-in mic makes you sound like you're calling from a submarine",
      ],
      buyOrCry: "buy",
    },
    reviews: [
      {
        author: "PartyAnimal_Goa",
        rating: 4,
        text: "Good speaker for the price. Bass is decent, gets loud enough. Don't expect JBL quality but it does the job at parties.",
        sarcasticTranslation:
          "A unicorn review: honest, calibrated, and acknowledges reality. This person should teach a masterclass in reviewing.",
        flagged: "genuine",
      },
      {
        author: "BassHead420",
        rating: 5,
        text: "BASS IS INSANE BRO!!! THIS THING SLAPS!!! 🔥🔥🔥",
        sarcasticTranslation:
          "Reviews written entirely in caps lock should automatically lose 2 stars. The fire emojis burn more than the speaker's actual bass.",
        flagged: "suspicious",
      },
    ],
  },
  {
    slug: "ergonomic-office-chair-lumbar-support",
    productName: "PosturePerfect Pro Ergonomic Office Chair",
    brand: "SitRight",
    category: "Furniture",
    images: {
      official: [
        "https://picsum.photos/seed/chair-official-1/400/400",
        "https://picsum.photos/seed/chair-official-2/400/400",
      ],
      review: [
        "https://picsum.photos/seed/chair-review-1/400/400",
        "https://picsum.photos/seed/chair-review-2/400/400",
      ],
    },
    sellerRating: 3.9,
    realityScore: 3.4,
    totalReviews: 3421,
    fakeReviewPercent: 38,
    price: "₹8,999",
    source: "amazon.in",
    sarcasticVerdict:
      "An 'ergonomic' chair where the lumbar support is just a pillow strapped to the back. For ₹8,999, your posture might not improve, but your buyer's remorse will be world-class.",
    whatTheySay:
      "Completely eliminated my back pain! Best investment for WFH!",
    whatTheyMean:
      "I stood up more often because sitting in this chair for more than an hour is a form of punishment. Less sitting = less back pain. Science!",
    serviceMetrics: {
      returnPolicy: "10-day return (heavy item surcharge)",
      returnSuccessRate: 41,
      deliveryRating: 3.0,
      customerSupportScore: 2.4,
      sellerResponseTime: "3-7 business days",
      sarcasticServiceVerdict:
        "Good luck returning a 15kg chair. The return pickup was 'attempted' three times while you were allegedly not home (you were). SitRight's support will offer you a ₹200 coupon instead of a refund every single time.",
    },
    aiAnalysis: {
      sentimentBreakdown: {
        genuine: 42,
        suspicious: 20,
        copypasta: 18,
        bribed: 20,
      },
      topSarcasticInsight:
        "The most honest signal? 42% genuine reviews — highest in our catalog. Turns out, spending ₹9K makes people care enough to write real reviews. Pain, financial and physical, is a great motivator.",
      realPros: [
        "Better than a dining chair (faint praise but true)",
        "Adjustable height actually works",
        "Assembly is manageable with mild cursing",
        "Mesh back provides ventilation in Indian summers",
      ],
      realCons: [
        "Armrests wobble after 3 months",
        "Lumbar support pillow flattens in 2 weeks",
        "Casters scratch hardwood floors",
        "Headrest angle is fixed in the 'stare at ceiling' position",
      ],
      buyOrCry: "maybe",
    },
    reviews: [
      {
        author: "WFH_Warrior",
        rating: 4,
        text: "Decent chair for the price range. Not Herman Miller obviously but much better than the ₹3K options. Assembly took 2 hours and some swearing.",
        sarcasticTranslation:
          "Realistic expectations + honest assembly time + profanity = the most trustworthy review formula known to humanity.",
        flagged: "genuine",
      },
      {
        author: "BackPainSurvivor",
        rating: 2,
        text: "The lumbar pillow deflated in a week. Now it's just a regular chair with extra steps. At least the box was useful for my cat.",
        sarcasticTranslation:
          "The cat getting more value from the purchase than the human is the most relatable review on the entire internet.",
        flagged: "genuine",
      },
    ],
  },
];

export function getProductBySlug(slug: string): ProductReview | undefined {
  return products.find((p) => p.slug === slug);
}

export function getAllSlugs(): string[] {
  return products.map((p) => p.slug);
}
